### ISSUE TITLE
🧐

### ISSUE THREAD

**Issue by neu5ron** [mutedmouse/HELK4SO#1]
RockNSM > SO 🙃

**Comment by mutedmouse** [comment]
I appreciate your interest in project.


As for myself, in nonfederated deployments, RockNSM is perfectly fine.
SecurityOnion, however, is significantly easier for analysts to deploy
federated sensors.

**Comment by mutedmouse** [comment]
Closed due to relevance.

**Comment by neu5ron** [comment]
sorry, I met Tilly week ago or so. Said I would give u a hard time for using SO.
I don’t disagree with your comment though :)
